/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-05-02 16:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.*;
import java.sql.*;
import javax.sql.*;
import java.io.*;

public final class db_002daction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Query Results</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1>Query Results</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String sql = request.getParameter("sql");
String sql2 = request.getParameter("sql2");
Context i = new InitialContext();
Context e = (Context) i.lookup("java:/comp/env");
DataSource d = (DataSource) e.lookup("jdbc/mydb");
Connection con = d.getConnection();

	if(sql2.length()>0){
		
		try{
		Statement st2 = con.createStatement();
			st2.executeUpdate(sql2);
		}catch (SQLException s){
      out.write("\r\n");
      out.write("\t\t\t<p>Update Error Stack</p><pre>");

			s.printStackTrace(new PrintWriter(out));
			
      out.write("\r\n");
      out.write("\t\t</pre>");

		}
	}	
if(sql.length()>0){
	try{
	Statement st = con.createStatement();
	ResultSet rs = st.executeQuery(sql);
	ResultSetMetaData md = rs.getMetaData();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" summary=\"query results\">\r\n");
      out.write("<tr>\r\n");
 for (int c=1; c<=md.getColumnCount(); c++) { 
      out.write("\r\n");
      out.write("  <th>");
      out.print( md.getColumnName(c));
      out.write("</th>\r\n");
 } 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 while (rs.next()) { 
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("  ");
 for (int c=1; c<=md.getColumnCount(); c++) { 
      out.write("\r\n");
      out.write("    <td>");
      out.print( rs.getString(c));
      out.write("</td>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("  </tr>\r\n");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

	}catch (SQLException s){
      out.write("\r\n");
      out.write("\t\t<p>Query Error Stack</p><pre>\r\n");
      out.write("\t\t");
s.printStackTrace(new PrintWriter(out));
      out.write("\r\n");
      out.write("</pre>\r\n");
      out.write("\t\t");

	}
}
con.close(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
