/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-05-05 12:43:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\r\n");
      out.write("  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("  lang=\"en-GB\" xml:lang=\"en-GB\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Odemia</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form enctype=\"multipart/form-data\" name=\"myForm\" action=\"register.jsp\" method=\"post\">   \r\n");
      out.write("  <h2>Login</h2>  \r\n");
      out.write("    <label for=\"userName\">User:</label>\r\n");
      out.write("    <input type=\"text\" name=\"userName\"/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <label for=\"passWord\">Password:</label>\r\n");
      out.write("    <input type=\"password\" name=\"passWord\"/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <label fro=\"email\">Email:</label>\r\n");
      out.write("    <input type=\"email\" name=\"email\"/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <label fro=\"firstName\">First Name:</label>\r\n");
      out.write("    <input type=\"text\" name=\"firstName\"/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <label fro=\"lastName\">Last Name:</label>\r\n");
      out.write("    <input type=\"text\" name=\"lastName\"/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <label fro=\"age\">Date of Birth:</label>\r\n");
      out.write("    <input type=\"date\" name=\"age\"/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <label fro=\"avatar\">Profile pic:</label>\r\n");
      out.write("    <input type=\"file\" name=\"avatar\"/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <input type=\"submit\"/>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
